define:
  config_file: <<cwd>>/experiments/<<project_id>>/<<datetime>>/<<job_idx>>/config.yml
  script_file: <<cwd>>/experiments/<<project_id>>/<<datetime>>/<<job_idx>>/run.sh
  log_file: <<cwd>>/experiments/<<project_id>>/<<datetime>>/<<job_idx>>/log.log
script_template: |
  python example/src/iris.py <<config_file>> > <<log_file>>
config_file: <<config_file>>
script_file: <<script_file>>
command: bash <<script_file>>
meta:
  project_id: iris_test
  name: try_min_samples_split
config:
  labels:
    itteration: 1
  cross_val_args:
    n_splits: 3
    shuffle: True
    random_state: 0
  model_args:
    n_estimators: 100
    max_depth: 2
    min_samples_leaf: 1
    random_state: 0
  dataset_args:
    target_column: species
    feature_columns:
      - sepal_length
      - sepal_width
      - petal_length
      - petal_width
  output_path: <<cwd>>/experiments/<<project_id>>/<<datetime>>/output.jsonl
grid:
  - - model_args:
        min_samples_split: 10
        min_samples_leaf: 1
      labels.min_samples: 'few_split_only'
    - model_args:
        min_samples_split: 10
        min_samples_leaf: 1
      labels.min_samples: 'many_split_only'
  - model_args.max_depth: [2,3]
    labels.max_depth: [2,3]